repository:
  name: song-modification-tool
  description: AI-powered audio processing tool
  homepage: https://abdulraheemnohri.github.io/song-modification-tool
  topics: audio-processing, machine-learning, python, flask
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: d73a4a
  - name: enhancement
    color: a2eeef
  - name: documentation
    color: 0075ca
  - name: help wanted
    color: 008672

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ['build']
      enforce_admins: true
      restrictions: null
