title: "Q&A: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Ask a question about the AI Song Modification Tool
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any relevant context or examples
